### ISSUE TITLE
Torus Wallet Issue

### ISSUE THREAD

**Issue by aitchis** [lorisleiva/solana-wallets-vue#15]
I've noticed an issue with the torus wallet adapter (that occurs in the demo too) and just wanted to make you aware @lorisleiva. When trying to connect when selected it raises this error: 

`WalletLoadError: process is not defined
    at TorusWalletAdapter.connect (vendor.bebbf726.js:127:107799)
    at async index.f1f974d4.js:1:3742`

I've had a quick look but haven't been able to find the cause of the issue. I was wondering if it was working before moving the wallet object to shallowRefs. 

Thanks for the great project!

**Comment by lorisleiva** [comment]
Hi there 👋

I've not used the Torus wallet personally but I think this is because [their own NPM package](https://github.com/solana-labs/wallet-adapter/tree/e15287221b90f8d7bee60726d251a5b4c76d243a/packages/wallets/torus) uses Node polyfills which are not available by default in most frontend bundlers.

The solution would be to polyfill `process` in your frontend. After fixing it, you might get a few other errors of the same type asking to polyfill more dependencies.

**Comment by aitchis** [comment]
Awesome, thanks for your quick response. I'll look into this, thanks again
