### ISSUE TITLE
Cannot connect iOS Phantom Wallet app

### ISSUE THREAD

**Issue by Aanhane** [lorisleiva/solana-wallets-vue#8]
I'm looking to make the connecting work on a Vue app, and the sample (https://solana-wallets-vue-demo.netlify.app/) also doesn't work for the Phantom iOS wallet, while it looks like the most recent version of the wallet adapter package is used I see. 

Any idea why this is not working? Can I help?

**Comment by lorisleiva** [comment]
Hi there 👋

Thanks for raising this! Yes, I notice this as well when playing with the Phantom mobile app. I'm not sure why it works with the react packages but not the Vue ones. I don't have much time to investigate right now but if anyone is able to help figure out what's happening that'd be amazing. ❤️

**Comment by NViktors** [comment]
Hi! 

I have checked this yesterday and so far discovered that there's an error after "Connect" button click.
It sounds like: "Cannot read private member from an object whose class did not declare it". But I haven't found jet which part exactly is causing this, because it's somewhat hard to debug without seeing console..

I will continue to investing this later on, so if I will find something - I will create PR or post about issue here.

**Comment by smitt04** [comment]
Does anyone know how to debug this? I can write a PR if i could figure out how to debug a page running in phantom app

**Comment by lorisleiva** [comment]
I can't manage to get the exact error message either. @NViktors how did you pull this off? 😅

**Comment by NViktors** [comment]
Hi! Sorry, I'm overloaded at the moment with my main job tasks.. :( 

How to reproduce:
1. Disable autoConnect option (in example/index.js)
2. Add debug alert to connect method catch block in WalletConnectButton.vue, like:
```js
connect().catch((e) => {
    alert(e);
})
```

After I got that error, I was 90% sure that this is adapter issue itself, so I pulled source from PhantomWalletAdapter and connected it directly for debugging purposes, like:

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/26169825/156153328-e27fdeab-18ba-4ceb-9e79-0ebc4f452256.png">

I did some debugging with alerts but haven't figured out what's wrong..

**Comment by lorisleiva** [comment]
Thanks, that's helpful. I'll do some debugging as well. 🙂

**Comment by NViktors** [comment]
Ok, now I'm confused.. 
I got this working with one line change/fix..?

In PhantomWalletAdapter, there is getter called `connected`:
```js
get connected(): boolean {
  return !!this._wallet?.isConnected;
}
```

But if I change this to:
```js
get connected(): boolean {
  return this._wallet && this._wallet.hasOwnProperty('isConnected') ? this._wallet.isConnected : false;
}
```

Then more error is gone and I'm able to successfully connect Phantom wallet.. 
What the ...?

@lorisleiva Can you try this and confirm?

**Comment by NViktors** [comment]
Well, but anyway it's not working, I'm unable to create new counter.. 
Will continue to debug this..

**Comment by lorisleiva** [comment]
Thanks for trying! I'll have a proper look at it this weekend.

**Comment by smitt04** [comment]
That looks good to me, i did try something a couple of days ago and came to the same conclusion that is was because of the `wallet.isConnected`, but got busy with other work to find a fix. If you have a branch or fork i could test it out for you

**Comment by NViktors** [comment]
@smitt04 https://github.com/NViktors/solana-wallets-vue/tree/test/phantom-adapter - I've pushed test code here

**Comment by smitt04** [comment]
@NViktors I tried to install the package and at first it would load with the initial yarn / npm install because the package wasn't built. So i tried to do a `yarn build` but it doesn't seem to want to connect in the normal browser, I also see no errors. I will try an do it another way when i have more time

**Comment by lorisleiva** [comment]
I found the root cause of the issue! In Vue 3, when using `ref` in an object, it makes the entire object reactive. This causes issues as Vue essentially takes ownership of the object which causes unpredictable behaviour on private attributes. The fix was simply to change `ref` for `shallowRef` on the `wallet` and the `wallets` properties of the wallet store. `shallowRef` ensures that the object is not deeply reactive which is exactly what we want.

You can now try the [demo app](https://solana-wallets-vue-demo.netlify.app/) in the Phantom mobile app and you'll be able to create a counter (if you have money on your devnet account).

![IMG_7952](https://user-images.githubusercontent.com/3642397/156888244-da7c8e1d-3fa2-404a-80a9-729ff5aa3398.PNG)
![IMG_7953](https://user-images.githubusercontent.com/3642397/156888249-1867e51a-15e8-4cae-abf0-5b9e3b449e15.PNG)
